### ISSUE TITLE
how to use this docker image with an exsit docusaurus project

### ISSUE THREAD

**Issue by xiongjiamu** [awesometic/docker-docusaurus#11]
HI, I got a problem with using your docker image with my local docusaurus project when I'm going to create a docker-compose.yml, every time when I used `docker-compose up` command , it always create a new Folder and won't work with my old docs.

here is my `docker-compose.yml`, can you show me how to use this docker image with an exsit docusaurus project? 

Thanks!

```yaml
version: '3'

services:
  docusaurus:
    image: awesometic/docusaurus:latest
    container_name: docusaurus
    build: .
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./docs:/docusaurus/docs
      - ./blog:/docusaurus/blog
      - ./src:/docusaurus/src
      - ./static:/docusaurus/static
      - ./sidebars.json:/docusaurus/sidebars.json
      - ./docusaurus.config.js:/docusaurus/docusaurus.config.js
    working_dir: /docusaurus
    command: 
      - npm run start
```

The Output likes:

```bash
...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 345.13s.
docusaurus  | 
docusaurus  | 
docusaurus  | Successfully created "MyWebsite".
docusaurus  | Inside that directory, you can run several commands:
docusaurus  | 
docusaurus  |   yarn start
docusaurus  |     Starts the development server.
docusaurus  | 
docusaurus  |   yarn build
docusaurus  |     Bundles your website into static files for production.
docusaurus  | 
docusaurus  |   yarn serve
docusaurus  |     Serves the built website locally.
docusaurus  | 
docusaurus  |   yarn deploy
docusaurus  |     Publishes the website to GitHub pages.
docusaurus  | 
docusaurus  | We recommend that you begin by typing:
docusaurus  | 
docusaurus  |   cd MyWebsite
docusaurus  |   yarn start
docusaurus  | 
docusaurus  | Happy building awesome websites!
docusaurus  | 
docusaurus  | npm notice 
docusaurus  | npm notice New major version of npm available! 8.19.2 -> 9.2.0
docusaurus  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
docusaurus  | npm notice Run `npm install -g npm@9.2.0` to update!
docusaurus  | npm notice 
docusaurus  | /* Node modules already exist in /docusaurus/MyWebsite/node_modules */
docusaurus  | /* Start supervisord to start Docusaurus... */
docusaurus  | 2022-12-29 07:48:50,213 INFO Set uid to user 0 succeeded
docusaurus  | 2022-12-29 07:48:50,220 INFO supervisord started with pid 88
docusaurus  | 2022-12-29 07:48:51,224 INFO spawned: 'docusaurus' with pid 89
docusaurus  | /* Will run this Node service as development mode... */
docusaurus  | yarn run v1.22.19
docusaurus  | $ docusaurus start --port 80 --host 0.0.0.0
docusaurus  | 2022-12-29 07:48:52,547 INFO success: docusaurus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
docusaurus  | Starting the development server...
docusaurus  | Docusaurus website is running at "http://localhost:80/".
docusaurus  | ℹ Compiling Client
docusaurus  | ℹ ｢wds｣: Project is running at http://0.0.0.0:80/
docusaurus  | ℹ ｢wds｣: webpack output is served from /
docusaurus  | ℹ ｢wds｣: Content not from webpack is served from /docusaurus/MyWebsite
docusaurus  | ℹ ｢wds｣: 404s will fallback to /index.html
docusaurus  | ✔ Client: Compiled successfully in 15.97s
```
